CREATE TABLE IF NOT EXISTS application (
	version VARCHAR(11)
);

CREATE TABLE IF NOT EXISTS users (
	id INT(11) PRIMARY KEY,
	username VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE
);